### ISSUE TITLE
[BUG/UX] - Going back is blocked till certain API calls succeed

### ISSUE THREAD

**Issue by hashkazi00** [documenso/documenso#442]
Summary:
There is a visible delay when the back CTA is pressed to go back. Seems like the API calls are blocking it.

SR:
https://github.com/documenso/documenso/assets/37013706/031c6b40-118f-44de-93d3-073f1420f450

**Comment by Mythie** [comment]
Hey there, not a bug but a fact of life when server rendering 😁

For each navigation Next will need to fetch and hydrate the component, this means that forward back navigation is somewhat bound by our ability to retrieve the data we need.

We could improve this by doing more on a client rather than the server but then we lose other benefits that I care about so I'd rather avoid it for now.
