### ISSUE TITLE
[Bug] The email is not resent if we update the email body

### ISSUE THREAD

**Issue by Abhinav-Developer-23** [documenso/documenso#544]
When we update the email body and send again, the emails are not being sent again even if no user has opened the link.

https://github.com/documenso/documenso/assets/145282438/5b01b024-cdbf-4b7a-86a4-7685c8757a82

1.Create a normal document signing with at least 2 recipients.
2.Do not open email from either of the email id.
3.Now go to the documenso dashboard and refresh the page.
4.click on the edit option.
5.Go to the third step where we enter email body and email subject.
6.update the email body and email subject and click on update.
7.You will get a notification that "Your document has beens sent successfully", but you will not get any email.

Expected Behavior
We should get email with updated email body and email subject

Current Behavior
We are not getting any email currently.

OS:ubuntu 22
Broswer:Google chrome beta (Version 118.0.5993.32 (Official Build) beta (64-bit))

- [x] I have searched the existing issues to make sure this is not a duplicate.
- [x] I have provided steps to reproduce the issue.
- [x] I have included relevant environment information.
- [x] I have included any relevant screenshots.
- [x] I understand that this is a voluntary contribution and that there is no guarantee of resolution.

**Comment by Abhinav-Developer-23** [comment]
I would like to work on this , if this is approved

**Comment by Mythie** [comment]
Hey there not sending the email to users who have already received one would be the right course of action even if the message or subject has been updated.

We could potentially offer a way to resend to all when we notice such a change has happened but for now it seems unnecessary. 

As a workaround we have #473 which aims to enable email resending which would address the gap in the short term since a document owner could decide to resend to all once they have updated the subject or message.

**Comment by Mythie** [comment]
Just want to add that we do appreciate the thought 🫶🏻
