### ISSUE TITLE
Can't cancel a Signature (as Signer)

### ISSUE THREAD

**Issue by daallgeier** [documenso/documenso#661]
### Issue Description

When on the Signature Page (and after adding my signature and the date) I can't cancel the process anymore.

### Steps to Reproduce

1. Get Link to Sign
2. Add your date and signature
3. Try to cancel

### Expected Behavior

Delete signature and date and show a confirmation of Cancelled signature (maybe even email the requestor).  I'd also expect it to show up in audit logs. 

### Current Behavior

It just does nothing other than animate the button. 

### Screenshots (optional)

![Screenshot 2023-11-17 at 16 54 59](https://github.com/documenso/documenso/assets/9637909/0bda3c69-71cf-4f38-9e96-5c72dcf99d31)

### Please check the boxes that apply to this issue report.

- [X] I have searched the existing issues to make sure this is not a duplicate.
- [X] I have provided steps to reproduce the issue.
- [X] I have included relevant environment information.
- [X] I have included any relevant screenshots.
- [X] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by Sahil-B07** [comment]
I'm really surprised and impressed with documenso I was unknown for this long, the service it provides is really helpful.
Would like to contribute for this feature 😀

**Comment by crediblebilal** [comment]
@daallgeier @Mythie When the Recipient clicks the `Cancel` button, he is redirected to the previous page from which he came on the `/sign/token` page. There are two scenarios here:
- If the Recipient is registered and logged in, and let's say he is on the documents page `/documents`, now if he/she clicks on the `Sign` button in the documents table, he will go to `/sign' page where he/she can sing the document. Now if he/she clicks the `Cancel` button here, he/she will be redirected to the previous page i.e. `/documents`, and then he/she can again click on the `Sign` button and sign the document.

- If the user is not a registered user and he opens the signing link from his email, he will directly go to the `/sign/token` page. Now here if he clicks the `Cancel` button, he should go to the previous page, but since there is no previous route history, that is why nothing happens here and it seems the `Cancel` button is doing nothing. If the user is on url `abc.com` and he directly pastes the signing URL in the search bar, on clicking the `Cancel` button he will be redirected back to `abc.com`.

@Mythie This can be solved once the flow expected behavior is properly defined!
