### ISSUE TITLE
[DOC-224] Bad Gateway Page and just a tiny quick error message (when sending to two recipients isnt possible) → not possibe to get back to the account via back button automatically, you need to use the back button and refresh the page

### ISSUE THREAD

**Issue by ElTimuro** [documenso/documenso#67]
<sub>From [SyncLinear.com](https://synclinear.com) | [DOC-224](https://linear.app/documenso/issue/DOC-224/bad-gateway-page-and-just-a-tiny-quick-error-message-when-sending-to)</sub>

**Comment by ElTimuro** [comment]
-Here is a loom of the error: https://www.loom.com/share/b66ffe679916408e87e27b27a620bd9a
- The invalid recipients should be ignored in backend
- Exceptions need to be caught at sending level and endpoint level, no endpoint should escalate to complete 502
- This escalates to the top level and is only healed by render restarting automatically
- This works suprisignly well, but is not sound
![image](https://user-images.githubusercontent.com/1309312/233611374-780601bd-c4ba-42b6-8965-ea422e4510ab.png)
![image](https://user-images.githubusercontent.com/1309312/233611525-ea2fc44e-ab1f-47b4-883e-b47055a0e186.png)
![image](https://user-images.githubusercontent.com/1309312/233611637-a7a5e73a-5d53-4129-b1fa-50803a60b78a.png)

@Mythie

**Comment by ElTimuro** [comment]
- @dephraiim True for the concrete error, but such an error maybe never bubble this high
- There is some architecture level Error Handling missing here

**Comment by Mythie** [comment]
Sounds great, first thing to do is handle exceptions in the method that sends the signing request to all members. Try to handle empty values or non email-like values gracefully by skipping them.

Use a simple regex like `.+@.+` for checking email validity since the standard for emails is quite funky.

If we encounter an error with sending it'd be nice to get either a 400 or 500 response with details that could be displayed within the toast so the user can action it.

e.g.

"We were unable to send the signing request to <email>, please ensure their email is correct and try again"

**Comment by Musacoli** [comment]
Hi @Mythie and @dephraiim ,
Is any one of you actively working on this? If not I'd like to take it up as my first issue.
