### ISSUE TITLE
CI/CD: .gitmodules with password protected repository breaks automated builds

### ISSUE THREAD

**Issue by b2cc** [documenso/documenso#79]
I recently wanted to gice Documenso a spin and configured an automated build on our Openshift cluster.
However this didn't work since the file:

* https://github.com/documenso/documenso/blob/main/.gitmodules

references a password-protected / non-public repository.

This breaks the build since the behavior to automatically check out repos specified in `.gitmodules`  files can't be turned off.
Would it be possible to remove this repo from `.gitmodules`?

Thanks for your work and support!

**Comment by ElTimuro** [comment]
Curious, since we are surely not the only repo doing it like this. The reference is just the project website, which is not open. Currently, there is no need to keep it there, so I just removed it.
---
- Btw: There is now a developer quickstart, spinning up a local environment for getting started faster: https://github.com/documenso/documenso#developer-quickstart
- Join us on Slack or create another Issue, if you have any more questions: https://join.slack.com/t/documenso/shared_invite/zt-1qwxxsvli-nDyojjt~wakhgBGl9JRl2w :)

**Comment by b2cc** [comment]
Thanks @ElTimuro !

**Comment by b2cc** [comment]
@ElTimuro :
Just recently came back to this and there is still a reference to an unaccessible path in the git filesystem. E.g. when running `git submodule update --init` this still gives an error on latest `main`:

```
Cloning "https://github.com/documenso/documenso" ...
error: fatal: No url found for submodule path 'documenso' in .gitmodules
```

`git ls-files` reveals the reference which needs to be cleared:
```
git ls-files --stage | grep 160000
160000 8039871ab15788312715737c3d4fd0f993fea6c1 0       documenso
```

Could you run:
```
git rm documenso
```
to clean that up? That should do it, worked for me locally.

Reference:
* https://stackoverflow.com/a/4185579

All the best, and thanks again for your help and consideration!

**Comment by ElTimuro** [comment]
@b2cc Hey just did. Sorry, this could have happened a lot sooner, my bad 😬
