### ISSUE TITLE
Soft-deleted documents still showing in the documents table

### ISSUE THREAD

**Issue by carlos-gn** [documenso/documenso#796]
After deleting a signed document (soft-deleting) [code related here](https://github.com/documenso/documenso/blob/341481d6dba8f91782e8e6787b7ddf3521064e19/packages/lib/server-only/document/delete-document.ts#L19-L20) the document still shows in the document list here:

<img width="1323" alt="image" src="https://github.com/documenso/documenso/assets/21148423/b18075fb-5089-4b7e-9553-5654b900b7c3">

I think it's because you are not filtering out the soft-delete documents in this query
https://github.com/documenso/documenso/blob/341481d6dba8f91782e8e6787b7ddf3521064e19/packages/lib/server-only/admin/get-all-documents.ts#L20-L46

**Comment by Nisarg-Sha** [comment]
I

https://github.com/documenso/documenso/assets/96575158/e54a925b-1c71-4861-bb25-bb8c50ec6ac4

It is working fine I checked with both pending & completed status.

**Comment by carlos-gn** [comment]
check this
https://github.com/documenso/documenso/assets/21148423/3e630883-e8e0-4170-9d15-9539d0aeab98

**Comment by carlos-gn** [comment]
i can fix it pretty quickly, if that's fine

**Comment by Mythie** [comment]
Hey there, looks like you’re a recipient of the sent document as well as the owner.

We let recipients keep a copy of the completed document even if the owner deletes it since Documenso should be a place to store all your docs.

if you test deleting a document where you are not also a recipient it should function as expected.

Admittedly this can be confusing in the UI since we also recognise you as an owner and should update that to handle post-deletion views

**Comment by carlos-gn** [comment]
Oh, that makes a lot of sense. maybe the problem is in the signature form, I guess it can be solved simply by not allowing users to set as recipient the same email as the owner of the document. solved anyways, thanks.
